package edu.usm.healthsystem.report;

import java.util.ArrayList;
import java.util.List;

public class HeaderGenerator {
	
	
    /**
     * @param clinic - The clinic the report is being generated for
     * @param district - The district the report is being generated in
     * @param region - The region the report is being generated in
     * @param name - The name of the client/employee generating the report
     * @return - The header of the report in 2D String format
     */
    public static List<String[]> addHeader(String clinic, String district, String region, String name) {
        List<String[]> reportHeader = new ArrayList<>();

        reportHeader.add(new String[] {"Family Planning Monthly Report", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""});
        reportHeader.add(new String[] {"Clinic: ", clinic, "", "", "", "", "", "", "", "", "", "", "", "", "", ""});
        reportHeader.add(new String[] {"District: ", district, "", "", "", "", "", "", "", "", "", "", "", "", "", ""});
        reportHeader.add(new String[] {"Region: ", region, "", "", "", "", "", "", "", "", "", "", "", "", "", ""});
        reportHeader.add(new String[] {"Report generated by: ", name, "", "", "", "", "", "", "", "", "", "", "", "", "", ""});
        reportHeader.add(new String[] {"STOCK", "", "LO-FEM", "Overette", "Male Condom", "Female Condom", 
                "Copper T", "Micro G", "Micr - N", "Postinor 2", "Sampoo", "Depo", "Vasectomy", "LAM", "Natural", "Norigynon"});

        return reportHeader;
    }
}